name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH private key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_vgen
          chmod 600 ~/.ssh/id_vgen  # Make sure the private key is not readable by others

      - name: Pull the latest code to VPS
        run: |
          ssh -i ~/.ssh/id_vgen root@64.225.52.191 'cd /var/www/vgen'
          ssh -i ~/.ssh/id_vgen root@64.225.52.191 'git reset --hard origin/main'

      - name: Build the project
        run: |
          ssh -i ~/.ssh/id_vgen root@64.225.52.191 'npm run build'

      - name: Re-run the process
        run: |
          ssh -i ~/.ssh/id_vgen root@64.225.52.191 'pm2 restart all'
          ssh -i ~/.ssh/id_vgen root@64.225.52.191 'pm2 save'
