name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_CISCO }}

      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 64.225.52.191 >> ~/.ssh/known_hosts

      - name: Pull the latest code to VPS
        run: |
          ssh root@64.225.52.191 'cd /var/www/vgen && git reset --hard origin/main'

      - name: Build the project
        run: |
          ssh root@64.225.52.191 'sudo ln -s /root/.nvm/versions/node/v20.18.1/bin/npm /usr/local/bin/npm && sudo ln -s /root/.nvm/versions/node/v20.18.1/bin/node /usr/local/bin/node && cd /var/www/vgen && /root/.nvm/versions/node/v20.18.1/bin/npm run build'

      - name: Re-run the process
        run: |
          ssh root@64.225.52.191 'sudo ln -s /root/.nvm/versions/node/v20.18.1/bin/pm2 /usr/local/bin/pm2 && pm2 restart all && pm2 save'
