name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo ${{secrets.SSH_IP}}
          ssh-keyscan -H ${{secrets.SSH_IP}} >> ~/.ssh/known_hosts

      - name: Pull the latest code to VPS
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_IP}} 'cd /var/www/vgen && git reset --hard origin/main'

      - name: Build the project
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_IP}} 'cd /var/www/vgen && npm run build'

      - name: Re-run the process
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_IP}} 'pm2 restart all && pm2 save'
