name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.1"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_CISCO }}

      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 64.225.52.191 >> ~/.ssh/known_hosts

      - name: Pull the latest code to VPS
        run: |
          ssh root@64.225.52.191 'cd /var/www/vgen'
          ssh root@64.225.52.191 'git reset --hard origin/main'

      - name: Build the project
        run: |
          ssh root@64.225.52.191 'npm run build'

      - name: Re-run the process
        run: |
          ssh root@64.225.52.191 'pm2 restart all'
          ssh root@64.225.52.191 'pm2 save'
